// Regenerates web/data/generated/* from the benchmark data in ../bench/data.
//   pnpm tsx scripts/export-data.ts
// Memory embeddings are read from bench/data/openai_embeddings.json, which
// `bench/run.py --systems openai` creates. They are stored as base64 float32.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const BENCH = join(__dirname, "..", "..", "bench", "data");
const OUT = join(__dirname, "..", "data", "generated");
mkdirSync(OUT, { recursive: true });

const memories = readFileSync(join(BENCH, "memories.txt"), "utf8")
  .split("\n")
  .filter((l) => l.includes("|") && !l.startsWith("#"))
  .map((l) => {
    const i = l.indexOf("|");
    return { id: l.slice(0, i).trim(), text: l.slice(i + 1).trim() };
  });

const scenarios = JSON.parse(readFileSync(join(BENCH, "scenarios.json"), "utf8"));
writeFileSync(join(OUT, "memories.json"), JSON.stringify({ today: scenarios.today, memories }, null, 1));

const emb = JSON.parse(readFileSync(join(BENCH, "openai_embeddings.json"), "utf8"));
if (JSON.stringify(emb.texts) !== JSON.stringify(memories.map((m) => m.text))) {
  throw new Error("openai_embeddings.json is stale: run `uv run --group bench python bench/run.py --systems openai`");
}
const dim = emb.vectors[0].length;
const flat = new Float32Array(memories.length * dim);
emb.vectors.forEach((v: number[], i: number) => flat.set(v, i * dim));
const b64 = Buffer.from(flat.buffer).toString("base64");
writeFileSync(
  join(OUT, "embeddings.ts"),
  `// Generated by scripts/export-data.ts. ${emb.model}, ${memories.length} x ${dim} float32, base64.\n` +
    `export const EMBEDDING_MODEL = ${JSON.stringify(emb.model)};\nexport const DIM = ${dim};\nexport const VECTORS_B64 = "${b64}";\n`,
);
console.log(`exported ${memories.length} memories, ${dim}-dim embeddings`);
